-- Intentionally no seed data here: inventory rows are keyed by product_id, which is
-- a UUID generated by product-catalog-service's own migration and is NOT known at
-- the time this migration file is written. Seeding inventory for the demo catalog
-- is done via a one-time script after both services are up - see README.md
-- ("Seeding inventory for the demo catalog"). This is a deliberate choice: writing
-- a fake/hardcoded UUID here would silently fail to match the real products and
-- create incident-detection tests that look like they pass but don't.
SELECT 1;
